name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.15
      - run: go test
<<<<<<< HEAD
      - run: go run math.go
=======
      - run: go run math.go
>>>>>>> 32f4aa2aa68621d28678e6cf568fec8349d2c058
